version: "3"

services:
  pruntime:
    image: phalanetwork/phala-pruntime:latest
    restart: always
    hostname: pruntime
    environment:
      - "ENABLE_KICK_API=1"
      - ROCKET_KEEP_ALIVE=60
      - ROCKET_READ_TIMEOUT=60
      - ROCKET_WRITE_TIMEOUT=60
    volumes:
      - "pruntime-data:/root/data"
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/provision:/dev/sgx/provision"
    ports:
      - "8000:8000"

volumes:
  pruntime-data:
