version: "3"

x-defaults: &defaults
  volumes: &default-volume-config
    - ../../..:/opt/app
    - ./data:/var/data

services:
  fetch:
    image: phalanetwork/poc4-prb:development
    build:
      context: ../../..
      dockerfile: docker/development/Dockerfile
    hostname: fetch
    depends_on:
      - redis
      - io
    volumes: *default-volume-config
    environment:
      - PHALA_MODULE=fetch
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=ws://path.to.phala.node
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  lifecycle:
    image: phalanetwork/poc4-prb:development
    hostname: lifecycle
    depends_on:
      - redis
      - io
    volumes: *default-volume-config
    environment:
      - PHALA_MODULE=lifecycle
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=ws://path.to.phala.node
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  trade:
    image: phalanetwork/poc4-prb:development
    hostname: trade
    depends_on:
      - redis
      - io
    volumes: *default-volume-config
    environment:
      - PHALA_MODULE=trade
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=ws://path.to.phala.node
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  io:
    << : *defaults
    image: phalanetwork/poc4-prb:development
    hostname: io
    restart: always
    environment:
      - PHALA_MODULE=io
      - NODE_ENV=development
      - PHALA_DB_HOST=io
      - PHALA_DB_PORT_BASE=9000
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_DB_PREFIX=/var/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "no"]
    restart: always
    hostname: redis
    ports:
      - "63791:6379"
