version: "3"

services:
  fetch:
    image: phalanetwork/poc4-prb:testing
    build:
      context: ../../..
      dockerfile: docker/testing/Dockerfile
    hostname: fetch
    volumes:
      - ./data:/var/data
    environment:
      - NODE_ENV=testing
      - PHALA_MODULE=fetch
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_DB_PREFIX=/var/data
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=wss://path.to.phala.node/ws
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  lifecycle:
    image: phalanetwork/poc4-prb:testing
    hostname: lifecycle
    volumes:
      - ./data:/var/data
    environment:
      - NODE_ENV=testing
      - PHALA_MODULE=lifecycle
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_DB_PREFIX=/var/data
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=wss://path.to.phala.node/ws
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  trade:
    image: phalanetwork/poc4-prb:testing
    hostname: trade
    environment:
      - NODE_ENV=testing
      - PHALA_MODULE=trade
      - PHALA_LOGGER_LEVEL=debug
      - PHALA_MAIN_CHAIN_ENDPOINT=
      - PHALA_CHAIN_ENDPOINT=wss://path.to.phala.node/ws
      - PHALA_REDIS_ENDPOINT=redis://redis:6379/

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "no"]
    restart: always
    hostname: redis
    ports:
      - "63791:6379"
