version: "3"

services:
  fetch:
    image: phalanetwork/poc4-prb:testing
    build:
      context: ../../..
      dockerfile: docker/testing/Dockerfile
    hostname: fetch
    environment:
      - NODE_ENV=tesing
      - DB_WAIT=0
    depends_on:
      - redis
      - couchbase
    command:
      [
        "pnpm", "bridge", "--",
        "f",
        "-r",
        "redis://redis:6379",
        "-c",
        "couchbase://couchbase/phala@phala:phalaphala",
        "-p",
        "wss://poc4.phala.network/ws",
      ]

  lifecycle:
    image: phalanetwork/poc4-prb:testing
    hostname: lifecycle
    environment:
      - NODE_ENV=tesing
      - DB_WAIT=0
    depends_on:
      - redis
      - couchbase
      - fetch
    ports:
      - 9229:9229
    command:
      [
        "pnpm", "bridge", "--",
        "lifecycle",
        "-r",
        "redis://redis:6379",
        "-c",
        "couchbase://couchbase/phala@phala:phalaphala",
        "-p",
        "wss://poc4.phala.network/ws",
      ]

  trade:
    image: phalanetwork/poc4-prb:testing
    hostname: trade
    deploy:
      replicas: 1 # for dev
    environment:
      - NODE_ENV=tesing
      - DB_WAIT=0
    depends_on:
      - redis
    command:
      [
        "pnpm", "bridge", "--",
        "trade",
        "-r",
        "redis://redis:6379",
        "-c",
        "couchbase://couchbase/phala@phala:phalaphala",
        "-p",
        "wss://poc4.phala.network/ws",
      ]

  arena:
    image: phalanetwork/poc4-prb:testing
    hostname: arena
    deploy:
      replicas: 1 # for dev
    environment:
      - NODE_ENV=testing
      - DB_WAIT=0
      - LOGGER_LEVEL=debug
    depends_on:
      - redis
    ports:
      - '4567:4567'
    command:
      [
        "pnpm", "node",
        "arena.js"
      ]

  couchbase:
    image: couchbase:community-7.0.0-beta
    hostname: couchbase
    volumes:
      - couchbase-data:/opt/couchbase/var
    ports:
      - "18091:8091"
    sysctls:
      net.core.somaxconn: 65535
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "no"]
    restart: always
    hostname: redis

volumes:
  couchbase-data:
